function createfigure(X1, Y1, X2, X3, Y2, X4)
%CREATEFIGURE(X1, Y1, X2, X3, Y2, X4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  X3:  vector of x data
%  Y2:  vector of y data
%  X4:  vector of x data

%  Auto-generated by MATLAB on 29-May-2025 00:43:54

% Create figure
figure1 = figure('Renderer','painters');

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',1,'Color',[0.5 0.5 0.5]);

% Create yline
yline(0,'Parent',subplot1,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create matlab.graphics.interactor.ListOfPointsHighlight
matlab.graphics.interactor.ListOfPointsHighlight('Visible','off',...
    'VertexData',zeros(3,0));

% Create ylabel
ylabel('$q$(kPa)','Interpreter','latex');

% Create xlabel
xlabel('$p$ (kPa)','Interpreter','latex');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-50 50]);
box(subplot1,'on');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'LineWidth',1,'YTick',[-50 -25 0 25 50]);
% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X2,Y1,'Parent',subplot2,'LineWidth',1,'Color',[0.5 0.5 0.5]);

% Create xline
xline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--',...
    'LineWidth',1);

% Create matlab.graphics.interactor.ListOfPointsHighlight
matlab.graphics.interactor.ListOfPointsHighlight('Visible','on',...
    'VertexData',[-0.0799999982118607 0.0799999982118607;0 0;0 0]);

% Create ylabel
ylabel('$q$ (kPa)','Interpreter','latex');

% Create xlabel
xlabel('$\varepsilon_1$(-)','Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[-0.08 0.08]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-50 50]);
box(subplot2,'on');
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'LineWidth',1,'XTick',[-0.08 -0.04 0 0.04 0.08],'YTick',...
    [-50 -25 0 25 50]);
% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X3,Y2,'Parent',subplot3,'LineWidth',0.9,'Color',[1 0 0]);

% Create yline
yline(0,'Parent',subplot3,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create matlab.graphics.interactor.ListOfPointsHighlight
matlab.graphics.interactor.ListOfPointsHighlight('Visible','off',...
    'VertexData',zeros(3,0));

% Create ylabel
ylabel('$ q$ (kPa)','Interpreter','latex');

% Create xlabel
xlabel('$p$ (kPa)','Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0 120]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[-50 50]);
box(subplot3,'on');
hold(subplot3,'off');
% Set the remaining axes properties
set(subplot3,'LineWidth',1,'YTick',[-50 -25 0 25 50]);
% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
hold(subplot4,'on');

% Create plot
plot(X4,Y2,'Parent',subplot4,'LineWidth',0.9,'Color',[1 0 0]);

% Create xline
xline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create matlab.graphics.interactor.ListOfPointsHighlight
matlab.graphics.interactor.ListOfPointsHighlight('Visible','off',...
    'VertexData',zeros(3,0));

% Create yline
yline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create matlab.graphics.interactor.ListOfPointsHighlight
matlab.graphics.interactor.ListOfPointsHighlight('Visible','off',...
    'VertexData',zeros(3,0));

% Create ylabel
ylabel('$q$ (kPa)','Interpreter','latex');

% Create xlabel
xlabel('$\varepsilon_1$(-)','Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[-0.08 0.08]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[-50 50]);
box(subplot4,'on');
hold(subplot4,'off');
% Set the remaining axes properties
set(subplot4,'LineWidth',1,'XTick',[-0.08 -0.04 0 0.04 0.08],'YTick',...
    [-50 -25 0 25 50]);
% Create textbox
annotation(figure1,'textbox',...
    [0.133635729239363 0.402055669747282 0.115688011764075 0.0434508804710446],...
    'String',{'Model response'},...
    'Interpreter','latex',...
    'FontSize',11,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.573970690858342 0.874763093328072 0.135134681783011 0.0434508804710445],...
    'String',{'Experimental data'},...
    'Interpreter','latex',...
    'FontSize',11,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.133286810886253 0.852053614684863 0.240383961267656 0.0677979136994127],...
    'String',{'Experimental data','$D_r = 62\%, p_0=100$kPa, $CSR=0.2$'},...
    'Interpreter','latex',...
    'FontSize',11,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.573621772505238 0.399326412105362 0.115688011764075 0.0434508804710446],...
    'String',{'Model response'},...
    'Interpreter','latex',...
    'FontSize',11,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.0774598743894009 0.420771516018215 0.0480607277473966 0.0484886627653683],...
    'String',{'(C)'},...
    'Interpreter','latex',...
    'FontSize',13,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.518492672714592 0.891013520640724 0.0478313923291823 0.0484886627653683],...
    'String',{'(B)'},...
    'Interpreter','latex',...
    'FontSize',13,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.517445917655275 0.422014252620735 0.0487488270434385 0.0484886627653683],...
    'String',{'(D)'},...
    'Interpreter','latex',...
    'FontSize',13,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.0764131193300846 0.902384280465029 0.0296580600139491 0.0376637544694426],...
    'String',{'(A)'},...
    'Interpreter','latex',...
    'FontSize',13,...
    'FitBoxToText','off',...
    'EdgeColor','none');

