% plotting section
%
% sand hypoplastic constitutive model
% array_sizes = size(SS);
% nrow = array_sizes(1);
%% TCUE RESULTS

% subplot(2,2,3)
% xx = INV_S(:,1); %(SS(:,3)+ SS(:,1))/2 
% yy = SS(:,3) - SS(:,1)
% 
% plot(xx,yy,'r-','linewidth',0.1)
% xlabel('$p$ (kPa)', 'interpreter', 'latex')
% ylabel('$ q$ (kPa)','interpreter','latex')
% yline(0, '--','color',[0.5 0.5 0.5], 'LineWidth', 1.0); % Línea horizontal en q = 50 kPa
% xlim([0,120])
% xlabel('$p$ (kPa)', 'interpreter', 'latex')
% ylabel('$ q$ (kPa)','interpreter','latex')
% % set(gca, 'XTicks', 0:20:120, 'YTicks', -50:25:50)
% xticks(0:20:120);xlim([0,120]);
% yticks(-90:30:90); ylim([-90,90]);
% set(gca, 'LineWidth', 0.7)
% text(-0.12, 1.05, '(C)', ...
%     'Units', 'normalized', ...
%     'FontWeight', 'bold', ...
%     'FontSize', 12, ...
%     'Interpreter', 'Latex', ...
%     'HorizontalAlignment', 'left', ...
%     'VerticalAlignment', 'top', ...
%     'Clipping', 'off')
% 
% 
% text(0.01, 0.98,...
%     {'\textbf{Model response}', ...
%      ''}, ...
%     'Units', 'normalized', ...
%     'Interpreter', 'latex', ...
%     'FontSize', 11, ...
%     'HorizontalAlignment', 'left', ...
%     'VerticalAlignment', 'top')
% 
% hold on
% 
% subplot(2,2,4)
% xx = EE(:,3)
% yy = SS(:,3)- SS(:,1)
% plot(xx,yy,'r-','linewidth',0.1);
% ylabel('$q$ (kPa)', 'interpreter', 'latex')
% xlabel('$\varepsilon_1$ \, (-)', 'Interpreter', 'latex')
% xline(0, '--','color',[0.5 0.5 0.5], 'LineWidth', 1.0); % Línea horizontal en q = 50 kPa
% yline(0, '--','color',[0.5 0.5 0.5], 'LineWidth', 1.0); % Línea horizontal en q = 50 kPa
% 
% ylabel('$q$ (kPa)', 'interpreter', 'latex')
% xlabel('$\varepsilon_1$ \, (-)', 'Interpreter', 'latex')
% xticks(-0.08:0.02:0.08);xlim([-0.08,0.08]);
% yticks(-90:30:90); ylim([-90,90]);
% set(gca, 'LineWidth', 0.7)
% text(-0.12, 1.05, '(D)', ...
%     'Units', 'normalized', ...
%     'FontWeight', 'bold', ...
%     'FontSize', 12, ...
%     'Interpreter', 'Latex', ...
%     'HorizontalAlignment', 'left', ...
%     'VerticalAlignment', 'top', ...
%     'Clipping', 'off')
% 
% text(0.01, 0.98,...
%     {'\textbf{Model response}', ...
%      ''}, ...
%     'Units', 'normalized', ...
%     'Interpreter', 'latex', ...
%     'FontSize', 11, ...
%     'HorizontalAlignment', 'left', ...
%     'VerticalAlignment', 'top')
% 
% hold on



% %%  PLOTS EXPORT .EPS ARTÍCULO (EPSA-Q AND P-Q)
% 
% subplot(4,2,3)
% xx = INV_S(:,1); %(SS(:,3)+ SS(:,1))/2 
% yy = SS(:,3) - SS(:,1)
% % % 
% plot(xx,yy,'b'); hold on
% 
% % plot(xx,yy,'color',[0.43 0.43 0.43]); hold on
% % xlabel('$p$ (kPa)', 'interpreter', 'latex')
% % ylabel('$ q$ (kPa)','interpreter','latex')
% % xline(9.1, '--','color',[0.5 0.5 0.5], 'LineWidth', 0.5); % Línea horizontal en q = 50 kPa
% % yline(0, ':','color',[0.4 0.4 0.4], 'LineWidth', 0.5); % Línea horizontal en q = 50 kPa
% % 
% % xlim([0,120])
% % 
% % xlabel('$p$ (kPa)', 'interpreter', 'latex')
% % ylabel('$ q$ (kPa)','interpreter','latex')
% % % set(gca, 'XTicks', 0:20:120, 'YTicks', -50:25:50)
% % xticks(0:20:120);xlim([0,120]);
% % % xline(4.65, '--','color',[0.5 0.5 0.5], 'LineWidth', 0.5); % Línea horizontal en q = 50 kPa
% % 
% yticks(-50:25:50); ylim([-50,50]);
% % yticks(-90:60:90); ylim([-90,90]);
% % yticks(-80:40:80); ylim([-80,80]);
% % set(gca, 'LineWidth', 0.7)
% % text(-0.21, 1.10, '(A)', ...
% %     'Units', 'normalized', ...
% %     'FontWeight', 'bold', ...
% %     'FontSize', 12, ...
% %     'Interpreter', 'Latex', ...
% %     'HorizontalAlignment', 'left', ...
% %     'VerticalAlignment', 'top', ...
% %     'Clipping', 'off')
% 
% % text(0.01, 0.98,...
% %     {'{Model response}', ...
% %      ''}, ...
% %     'Units', 'normalized', ...
% %     'Interpreter', 'latex', ...
% %     'FontSize', 11, ...
% %     'HorizontalAlignment', 'left', ...
% %     'VerticalAlignment', 'top')
% 
% % hold on
% % 
% % phi_cs = 33;                         % ángulo de fricción crítica en grados
% % M = (6 * sind(phi_cs)) / (3 - sind(phi_cs));  % pendiente de la CSL
% % % Eje de presión media
% % p_vals = linspace(0, 100, 100);     % Ajusta el rango según tu gráfica
% % % Línea CSL
% % q_vals = M * p_vals;
% % 
% % plot(p_vals, 1.1*q_vals, 'r'); hold on    % CSL positiva
% % plot(p_vals, -0.77*q_vals, 'r');    hold on    % CSL negativa
% 
% subplot(2,2,4)
% xx = EE(:,3)
% yy = SS(:,3)- SS(:,1)
% plot(xx,yy,'b'); hold on
% % plot(xx,yy,'color',[0.43 0.43 0.43]);
% ylabel('$q$ (kPa)', 'interpreter', 'latex')
% xlabel('$\varepsilon_1$ \, (-)', 'Interpreter', 'latex')
% xline(0,':','color',[0.4 0.4 0.4]);
% yline(0,':','color',[0.4 0.4 0.4]);
% yticks(-50:25:50); ylim([-50,50]);
% xticks(-0.08:0.04:0.08);xlim([-0.08,0.08]);
% 
% % yticks(-60:20:60); ylim([-60,60]);
% % yticks(-90:60:90); ylim([-9,90]);
% % yticks(-80:40:80); ylim([-80,80]);
% 
% 
% set(gca, 'LineWidth', 0.7)
% text(-0.21, 1.10, '(B)', ...
%     'Units', 'normalized', ...
%     'FontWeight', 'bold', ...
%     'FontSize', 12, ...
%     'Interpreter', 'Latex', ...
%     'HorizontalAlignment', 'left', ...
%     'VerticalAlignment', 'top', ...
%     'Clipping', 'off')
% 
% % text(0.01, 0.98,...
% %     {'{Model response}', ...
% %      ''}, ...
% %     'Units', 'normalized', ...
% %     'Interpreter', 'latex', ...
% %     'FontSize', 11, ...
% %     'HorizontalAlignment', 'left', ...
% %     'VerticalAlignment', 'top')

%%  Clibration Cx and eta

% subplot(3,4,7)
% % figure();
% xx = INV_S(:,1); %(SS(:,3)+ SS(:,1))/2 
% yy = SS(:,3) - SS(:,1)
% 
% plot(xx,yy,'b-','linewidth',0.1); hold on
% xlabel('$p$ (kPa)', 'interpreter', 'latex')
% ylabel('$ q$ (kPa)','interpreter','latex')
% yline(0, '--','color',[0.5 0.5 0.5], 'LineWidth', 0.5); % Línea horizontal en q = 50 kPa
% 
% xticks(0:20:120);xlim([0,120]);
% yticks(-50:25:50); ylim([-50,50]);
% % yticks(-90:30:90); ylim([-90,90]);
% set(gca, 'LineWidth', 0.7)
% text(-0.18, 1.05, '(E)', ...
%     'Units', 'normalized', ...
%     'FontWeight', 'bold', ...
%     'FontSize', 12, ...
%     'Interpreter', 'Latex', ...
%     'HorizontalAlignment', 'left', ...
%     'VerticalAlignment', 'top', ...
%     'Clipping', 'off')
% 
% phi_cs = 33;                         % ángulo de fricción crítica en grados
% M = (6 * sind(phi_cs)) / (3 - sind(phi_cs));  % pendiente de la CSL
% % Eje de presión media
% p_vals = linspace(0, 100, 100);     % Ajusta el rango según tu gráfica
% % Línea CSL
% q_vals = M * p_vals;
% 
% plot(p_vals, 1.1*q_vals, 'r'); hold on    % CSL positiva
% plot(p_vals, -0.77*q_vals, 'r');    hold on    % CSL negativa
% 
% 
% % hold on

%% CALIBRATION OF a01
% figure()

phi_cs = 34;                         % ángulo de fricción crítica en grados
M = (6 * sind(phi_cs)) / (3 - sind(phi_cs));  % pendiente de la CSL
% Eje de presión media
p_vals = linspace(0, 100, 100);     % Ajusta el rango según tu gráfica
% Línea CSL
q_vals = M * p_vals;




subplot(2,2,3)
xx = INV_S(:,1); %(SS(:,3)+ SS(:,1))/2 
yy = SS(:,3) - SS(:,1)

% plot(p_vals, 0.7*q_vals, 'r'); hold on    % CSL positiva
% plot(p_vals, -2.0*q_vals, 'r');    hold on    % CSL negativa

% plot(xx(1:end),yy(1:end),'color',[0.60,0.35,0.60]); hold on
plot(xx(1:end),yy(1:end),'-'); hold on
xline(0,'--','color',[0.5 0.7 0.7]); yline(0,'--','color',[0.7 0.7 0.7]);
% yticks(-60:30:60); ylim([-60,60]);ylabel('$q$ (kPa)','interpreter','latex')
% yticks(-50:25:50); ylim([-50,50]);ylabel('$q$ (kPa)','interpreter','latex')
xlim([-10 120]); xlabel('$p$ (kPa)','interpreter','latex')
% yticks(-100:50:100); ylim([-100,100]);ylabel('$q$ (kPa)','interpreter','latex')
% yticks(-60:20:60); ylim([-60,60]);ylabel('$q$ (kPa)','interpreter','latex')


text(0.01, 0.98,...
    {'{Model response}', ...
     ''}, ...
    'Units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontSize', 10, ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'top')

text(-0.15, 1.05, '(C)', ...
    'Units', 'normalized', ...
    'FontWeight', 'bold', ...
    'FontSize', 10, ...
    'Interpreter', 'Latex', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'top', ...
    'Clipping', 'off')


subplot(2,2,4)
xx = EE(:,3)
yy = SS(:,3)- SS(:,1)
% plot(xx(1:1700),yy(1:1700),'r'); hold on
% plot(xx(1:end),yy(1:end),'color',[0.6,0.35,0.60]); hold on
plot(xx(1:end),yy(1:end),'-'); hold on
% plot(xx(1:end),yy(1:end),'r'); hold on
% xlim([-0.04 0.015])
% xlim([-0.06, 0.06]);ylim([-60, 60]);
xlim([-0.06, 0.06]);
% yticks(-60:20:60); ylim([-60,60]);ylabel('$q$ (kPa)','interpreter','latex')
% yticks(-100:50:100); ylim([-100,100]);ylabel('$q$ (kPa)','interpreter','latex')

% plot(xx,yy,'color',[0.43 0.43 0.43]);
ylabel('$q$ (kPa)', 'interpreter', 'latex')
xlabel('$\varepsilon_1$ \, (-)', 'Interpreter', 'latex')
xline(0,'--','color',[0.7 0.7 0.7]); yline(0,'--','color',[0.7 0.7 0.7]);
text(0.01, 0.98,...
    {'{Model response}', ...
     ''}, ...
    'Units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontSize', 10, ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'top')

text(-0.15, 1.05, '(D)', ...
    'Units', 'normalized', ...
    'FontWeight', 'bold', ...
    'FontSize', 10, ...
    'Interpreter', 'Latex', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'top', ...
    'Clipping', 'off')
