function createfigure1(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, X8, X9, X10, X11, X12, X13, Y7, X14, Y8, X15, Y9, X16, Y10, X17, Y11, X18, Y12, X19, X20, X21, X22, X23, X24)
%CREATEFIGURE1(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, X8, X9, X10, X11, X12, X13, Y7, X14, Y8, X15, Y9, X16, Y10, X17, Y11, X18, Y12, X19, X20, X21, X22, X23, X24)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data
%  X5:  vector of x data
%  Y5:  vector of y data
%  X6:  vector of x data
%  Y6:  vector of y data
%  X7:  vector of x data
%  X8:  vector of x data
%  X9:  vector of x data
%  X10:  vector of x data
%  X11:  vector of x data
%  X12:  vector of x data
%  X13:  vector of x data
%  Y7:  vector of y data
%  X14:  vector of x data
%  Y8:  vector of y data
%  X15:  vector of x data
%  Y9:  vector of y data
%  X16:  vector of x data
%  Y10:  vector of y data
%  X17:  vector of x data
%  Y11:  vector of y data
%  X18:  vector of x data
%  Y12:  vector of y data
%  X19:  vector of x data
%  X20:  vector of x data
%  X21:  vector of x data
%  X22:  vector of x data
%  X23:  vector of x data
%  X24:  vector of x data

%  Auto-generated by MATLAB on 24-Jun-2025 16:26:38

% Create figure
figure1 = figure('InvertHardcopy','off','WindowState','maximized',...
    'Color',[1 1 1],...
    'Renderer','painters');

% Create subplot
subplot1 = subplot(2,2,3,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',0.1,'Color',[1 0 0]);

% Create yline
yline(0,'Parent',subplot1,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create text
text('Parent',subplot1,'Units','normalized','VerticalAlignment','top',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Interpreter','latex',...
    'String','(C)',...
    'Position',[-0.14 1.05 0]);

% Create text
text('Parent',subplot1,'Units','normalized','VerticalAlignment','top',...
    'FontSize',11,...
    'Interpreter','latex',...
    'String',{'Model response'},...
    'Position',[0.01 0.98 0]);

% Create plot
plot(X2,Y2,'Parent',subplot1,'LineWidth',0.1,'Color',[1 0 0]);

% Create yline
yline(0,'Parent',subplot1,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X3,Y3,'Parent',subplot1,'LineWidth',0.1,'Color',[1 0 0]);

% Create yline
yline(0,'Parent',subplot1,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X4,Y4,'Parent',subplot1,'LineWidth',0.1,'Color',[1 0 0]);

% Create yline
yline(0,'Parent',subplot1,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X5,Y5,'Parent',subplot1,'LineWidth',0.1,'Color',[1 0 0]);

% Create yline
yline(0,'Parent',subplot1,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X6,Y6,'Parent',subplot1,'LineWidth',0.1,'Color',[1 0 0]);

% Create yline
yline(0,'Parent',subplot1,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot1,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot1,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot1,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create ylabel
ylabel('$ q$ (kPa)','Interpreter','latex');

% Create xlabel
xlabel('$p$ (kPa)','Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 400]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-300 450]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(subplot1,[-1 1]);
box(subplot1,'on');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'LineWidth',0.8,'XTick',[0 100 200 300 400 500 600],'YTick',...
    [-300 -150 0 150 300 450]);
% Create subplot
subplot2 = subplot(2,2,4,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X7,Y1,'Parent',subplot2,'LineWidth',0.1,'Color',[1 0 0]);

% Create xline
xline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create text
text('Parent',subplot2,'Units','normalized','VerticalAlignment','top',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Interpreter','latex',...
    'String','(D)',...
    'Position',[-0.14 1.05 0]);

% Create text
text('Parent',subplot2,'Units','normalized','VerticalAlignment','top',...
    'FontSize',11,...
    'Interpreter','latex',...
    'String',{'Model response'},...
    'Position',[0.01 0.98 0]);

% Create plot
plot(X8,Y2,'Parent',subplot2,'LineWidth',0.1,'Color',[1 0 0]);

% Create xline
xline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X9,Y3,'Parent',subplot2,'LineWidth',0.1,'Color',[1 0 0]);

% Create xline
xline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X10,Y4,'Parent',subplot2,'LineWidth',0.1,'Color',[1 0 0]);

% Create xline
xline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X11,Y5,'Parent',subplot2,'LineWidth',0.1,'Color',[1 0 0]);

% Create xline
xline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X12,Y6,'Parent',subplot2,'LineWidth',0.1,'Color',[1 0 0]);

% Create xline
xline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot2,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create ylabel
ylabel('$q$ (kPa)','Interpreter','latex');

% Create xlabel
xlabel('$\varepsilon_1$ \, (-)','Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[-0.1 0.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-500 1000]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(subplot2,[-1 1]);
box(subplot2,'on');
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'LineWidth',0.8,'XTick',[-0.1 -0.05 0 0.05 0.1],'YTick',...
    [-500 0 500 1000]);
% Create subplot
subplot3 = subplot(2,2,1,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X13,Y7,'Parent',subplot3,'Color',[0 0 1]);

% Create yline
yline(0,'Parent',subplot3,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create text
text('Parent',subplot3,'Units','normalized','VerticalAlignment','top',...
    'FontSize',11,...
    'Interpreter','latex',...
    'String','(A)',...
    'Position',[-0.14 1.05 0]);

% Create plot
plot(X14,Y8,'Parent',subplot3,'Color',[0 0 1]);

% Create yline
yline(0,'Parent',subplot3,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X15,Y9,'Parent',subplot3,'Color',[0 0 1]);

% Create yline
yline(0,'Parent',subplot3,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X16,Y10,'Parent',subplot3,'Color',[0 0 1]);

% Create yline
yline(0,'Parent',subplot3,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X17,Y11,'Parent',subplot3,'Color',[0 0 1]);

% Create yline
yline(0,'Parent',subplot3,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X18,Y12,'Parent',subplot3,'Color',[0 0 1]);

% Create yline
yline(0,'Parent',subplot3,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create matlab.graphics.interactor.ListOfPointsHighlight
matlab.graphics.interactor.ListOfPointsHighlight('Visible','off',...
    'VertexData',zeros(3,0));

% Create text
text('Parent',subplot3,'Units','normalized','VerticalAlignment','top',...
    'FontSize',11,...
    'Interpreter','latex',...
    'String',{'Experimental data','$p_0=200$kPa'},...
    'Position',[0.0172202164989087 0.976894409937888 0]);

% Create ylabel
ylabel('$q$ (kPa)','Interpreter','latex');

% Create xlabel
xlabel('$p$ (kPa)','Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0 400]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[-300 450]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(subplot3,[-1 1]);
box(subplot3,'on');
hold(subplot3,'off');
% Set the remaining axes properties
set(subplot3,'LineWidth',0.8,'XTick',[0 100 200 300 400 500 600],'YTick',...
    [-300 -150 0 150 300 450]);
% Create subplot
subplot4 = subplot(2,2,2,'Parent',figure1);
hold(subplot4,'on');

% Create plot
plot(X19,Y7,'Parent',subplot4,'Color',[0 0 1]);

% Create xline
xline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create text
text('Parent',subplot4,'Units','normalized','VerticalAlignment','top',...
    'FontSize',11,...
    'Interpreter','latex',...
    'String','(B)',...
    'Position',[-0.14 1.05 0]);

% Create plot
plot(X20,Y8,'Parent',subplot4,'Color',[0 0 1]);

% Create xline
xline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X21,Y9,'Parent',subplot4,'Color',[0 0 1]);

% Create xline
xline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X22,Y10,'Parent',subplot4,'Color',[0 0 1]);

% Create xline
xline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X23,Y11,'Parent',subplot4,'Color',[0 0 1]);

% Create xline
xline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create plot
plot(X24,Y12,'Parent',subplot4,'Color',[0 0 1]);

% Create xline
xline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create yline
yline(0,'Parent',subplot4,'Color',[0.5 0.5 0.5],'LineStyle','--');

% Create text
text('Parent',subplot4,'Units','normalized','VerticalAlignment','top',...
    'FontSize',11,...
    'Interpreter','latex',...
    'String',{'Experimental data','$p_0=200$kPa'},...
    'Position',[0.0172202164989087 0.976894409937888 0]);

% Create ylabel
ylabel('$q$ (kPa)','Interpreter','latex');

% Create xlabel
xlabel('$\varepsilon_1$ (-)','Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[-0.1 0.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[-500 1000]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(subplot4,[-1 1]);
box(subplot4,'on');
hold(subplot4,'off');
% Set the remaining axes properties
set(subplot4,'LineWidth',0.8,'XTick',[-0.1 -0.05 0 0.05 0.1],'YTick',...
    [-500 0 500 1000]);
% Create arrow
annotation(figure1,'arrow',[0.163845223700121 0.175634824667474],...
    [0.666666666666665 0.693650793650786],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.183494558645708 0.195284159613061],...
    [0.17195767195767 0.198941798941791],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.224304715840387 0.244860943168078],...
    [0.626455026455026 0.682539682539679],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.237908101571947 0.258464328899638],...
    [0.148677248677248 0.204761904761901],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.292019347037485 0.272067714631197],...
    [0.787301587301588 0.764021164021164],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.307738814993954 0.285066505441356],...
    [0.658201058201058 0.674603174603172],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.304111245465538 0.285368802902058],...
    [0.171428571428571 0.196825396825393],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.313180169286578 0.292321644498187],...
    [0.318518518518519 0.293650793650793],'HeadWidth',8);

% Create textbox
annotation(figure1,'textbox',...
    [0.292019347037486 0.767116652280551 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 87\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.308041112454657 0.636428821592728 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 98\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.199516324062879 0.596746281910189 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 58\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.136336154776301 0.635370620534527 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 29\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.291717049576784 0.311561096725013 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 87\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.283555018137849 0.142778027941935 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 98\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.213724304715842 0.11896850413241 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 58\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.16082224909311 0.141719826883733 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 29\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.635429262394199 0.719497604661486 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 29\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.64238210399033 0.223730408894315 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 29\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.6130592503023 0.155476440640346 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 58\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.725211608222495 0.111561096725003 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 98\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create arrow
annotation(figure1,'arrow',[0.668379685610643 0.684401451027812],...
    [0.23121693121693 0.207407407407407],'HeadWidth',8);

% Create textbox
annotation(figure1,'textbox',...
    [0.720072551390571 0.354418239582155 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 87\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create arrow
annotation(figure1,'arrow',[0.747883917775093 0.763905683192262],...
    [0.360846560846559 0.337037037037037],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.819528415961306 0.802599758162036],...
    [0.222751322751323 0.251322751322743],'HeadWidth',8);

% Create textbox
annotation(figure1,'textbox',...
    [0.79746070133011 0.192513477677385 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 34\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.819528415961307 0.32320130836522 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 68\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create arrow
annotation(figure1,'arrow',[0.636638452237004 0.652660217654173],...
    [0.164021164021163 0.14021164021164],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.746674727932286 0.729746070133015],...
    [0.137566137566137 0.166137566137558],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.637847642079808 0.627267230955266],...
    [0.625396825396824 0.652380952380942],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.6590084643289 0.668379685610643],...
    [0.725925925925926 0.698941798941793],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.797460701330109 0.780834340991543],...
    [0.852910052910053 0.885185185185174],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.845223700120919 0.830411124546561],...
    [0.679365079365079 0.712698412698401],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.840689238210399 0.823760580411129],...
    [0.355026455026454 0.383597883597875],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.808343409915357 0.787787182587671],...
    [0.760846560846561 0.754497354497344],'HeadWidth',8);

% Create textbox
annotation(figure1,'textbox',...
    [0.805320435308344 0.742778027941923 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 68\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.779625151148733 0.824788609952491 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 87\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.82255139056832 0.651243636407533 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 34\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.707980652962519 0.591455276619181 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 98\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create arrow
annotation(figure1,'arrow',[0.7273276904474 0.714631197097952],...
    [0.622222222222222 0.646560846560836],'HeadWidth',8);

% Create textbox
annotation(figure1,'textbox',...
    [0.615779927448611 0.596217181381088 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 58\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.236396614268441 0.366058451222364 0.0552145227708571 0.0334706493067324],...
    'String',{'$D_r = 68\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.188331318016931 0.331666916830821 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 34\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create arrow
annotation(figure1,'arrow',[0.259371221281741 0.27025392986699],...
    [0.369312169312169 0.299470899470897],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.236094316807739 0.246977025392988],...
    [0.833333333333331 0.763492063492059],'HeadWidth',8);

% Create textbox
annotation(figure1,'textbox',...
    [0.209492140266022 0.830079615243518 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 68\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

% Create arrow
annotation(figure1,'arrow',[0.214026602176542 0.219165659008466],...
    [0.337566137566137 0.307407407407399],'HeadWidth',8);

% Create arrow
annotation(figure1,'arrow',[0.17261185006046 0.177750906892384],...
    [0.791005291005289 0.760846560846551],'HeadWidth',8);

% Create textbox
annotation(figure1,'textbox',...
    [0.14752116082225 0.78510607026997 0.055214522770857 0.0334706493067324],...
    'String',{'$D_r = 34\%$'},...
    'Interpreter','latex',...
    'EdgeColor','none');

